GET http://localhost:3009/

###
GET http://localhost:3009/products


###
GET http://localhost:3009/users/12345/cart

###
GET http://localhost:3009/products/123

###
POST http://localhost:3009/users/12345/cart
Content-Type: application/json

{
    "productId": 456
}

###
DELETE  http://localhost:3009/users/12345/cart/456
Content-Type: application/json
